# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            SRLM
tagline:          'Programming and Hardware'
url:              http://srlmproductions.com
paginate:         1
baseurl:          /
author:
  name:           Cody Lewis
  url:            https://github.com/srlmproductions.com
  email:          srlm@srlmproductions.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/srlmproductions
