# Dependencies
markdown:         redcarpet
# Make redcarpet behave like GitHub Flavored Markdown
# Taken from http://stackoverflow.com/a/16126840/2557842
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            SRLM
tagline:          'Programming and Hardware'
url:              http://srlm.io
paginate:         4
baseurl:          /
author:
  name:           Cody Lewis
  url:            https://github.com/srlmproductions
  email:          srlm@srlm.io

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/srlmproductions

excerpt_separator: <!--endexcerpt-->