# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            SRLM
tagline:          'Programming and Hardware'
url:              http://srlm.io
paginate:         4
baseurl:          /
author:
  name:           Cody Lewis
  url:            https://github.com/srlmproductions
  email:          srlm@srlm.io

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/srlmproductions
